### ISSUE TITLE
Kotlin sample app

### ISSUE THREAD

**Issue by provJoshMieczkowski** [GYANTINC/gyant-android-sdk#1]
Hello,

I am trying out the kotlin sample app and there seems to be a compiler error. In `DisplayGyantViewWithPushTokenActivity`, it is asking to implement `override fun getToken(callback: CompletionHandler<*>)` and currently you guys have `override fun getToken(callback: CompletionHandler)`

In your interface `GyantOnPushTokenListener` you should either allow a type to be passed
```
public interface GyantOnPushTokenListener<T> {
    void getPushToken(CompletionHandler<T> var1);
}
```
or
```
public interface GyantOnPushTokenListener {
    void getPushToken(CompletionHandler<String> var1);
}
```

**Comment by vitor-gyant** [comment]
@provJoshMieczkowski The issue is now solved. Please, verify it with the new 1.0.9 release. Thanks

**Comment by provJoshMieczkowski** [comment]
It is working now! Thanks guys :D
